apply plugin: 'com.android.application'

android {
    compileSdkVersion 35
    defaultConfig {
        namespace "com.beeinc.libnative"
        applicationId "com.beeinc.nativedata"
        ndkVersion "29.0.14206865"
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
        externalNativeBuild {
            cmake {
                arguments "-DOpenCV_DIR=" + project(':opencv').projectDir + "/native/jni",
                        "-DANDROID_TOOLCHAIN=clang",
                        "-DANDROID_STL=c++_shared"
                targets "detection_based_tracker"
            }
        }
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    flavorDimensions "color"
    productFlavors {
        sqsmm {
            dimension "color"
            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "sqsmm"]
        }
    }
    lint {
        abortOnError false // ✅ correct place
        baseline = file("lint-baseline.xml") // optional
    }
    signingConfigs {
        //正式签名
        debug {
            storeFile file('../sqsb.keystore')//签名文件路径
            storePassword "123456"
            keyAlias "sqsb"
            keyPassword "123456"  //签名密码
            v1SigningEnabled true
            v2SigningEnabled true
        }
        release {
            storeFile file('../sqsb.keystore')//签名文件路径
            storePassword "123456"
            keyAlias "sqsb"
            keyPassword "123456"  //签名密码
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }
    android.buildFeatures.buildConfig true
    buildTypes {
        debug {
            println("====== buildTypes.debug ======")
            buildConfigField("boolean", "LOG_DEBUG", "true");       //网络请求是否开启日志模式
            //内网
            buildConfigField("String", "BASE_URL", "\"http://192.168.32.26:10002/\"");
            signingConfig signingConfigs.debug
        }
        release {
            buildConfigField("boolean", "LOG_DEBUG", "false");       //网络请求是否开启日志模式
            buildConfigField("String", "BASE_URL", "\"http://192.168.32.26:10002/\"");
            buildConfigField("String", "BASE_SOCKET", "\"192.168.32.26\"");
            signingConfig signingConfigs.release
            // 自定义输出配置
            applicationVariants.all { variant ->
                variant.outputs.all {
                    outputFileName = "beenic_v${defaultConfig.versionName}_${variant.productFlavors[0].name}.apk"
                }
            }
        }
    }
    externalNativeBuild {
        cmake {
            path 'jni/CMakeLists.txt'
        }
    }
}
repositories {
    flatDir {
        dirs 'libs'
    }
}
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation project(':album')
    implementation project(':okhttp')
    implementation project(':mylibrary')
    implementation project( ':myaars:opencv-release')
}
